name: publish-to-docker

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Set version
        run: echo VERSION=`date +%Y%m%d` >> $GITHUB_ENV

      - name: Check version
        run: echo Building version ${{ env.VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            platforms: linux/amd64,linux/arm64
            driver-opts: | 
                image=moby/buildkit:v0.10.6

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.dsezer.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: docker.dsezer.dev/sites/static:latest,docker.dsezer.dev/sites/static:${{ env.VERSION }}